---
- hosts: localhost
  gather_facts: no
  tasks:

    - name: Create VPC
      ec2_vpc_net:
        name: m5-image-gallery
        cidr_block: 10.10.0.0/16
        region: "us-east-2"
        tags:
          Module: 5
        state: present
      register: vpc

    - name: Create public subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "us-east-2"
        az: "us-east-2a"
        tags:
          Name: M5-public-sn
          Module: 5
        cidr: 10.10.0.0/24
        state: present
      register: pubsub1

    - name: Create 2nd public subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        az: "us-east-2c"
        tags:
          Name: M5-public-sn-2
          Module: 5
        cidr: 10.10.2.0/24
        state: present
      register: pubsub2

    - name: Create private subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        az: "us-east-2a"
        tags:
          Name: M5-private-sn
          Module: 5
        cidr: 10.10.1.0/24
        state: present  
      register: privsub1 

    - name: Create 2nd private subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        az: "us-east-2b"
        tags:
          Name: M5-private-sn-2
          Module: 5
        cidr: 10.10.3.0/24
        state: present 
      register: privsub2  

    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: M5-igw
        state: present
      register: igw        

    - name: Create public route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: M5-public-rt
        subnets:
          - "{{ pubsub1.subnet.id }}"        
          - "{{ pubsub2.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
        state: present
      register: public_route_table        

    - name: Create NAT Gateway
      ec2_vpc_nat_gateway:
        subnet_id: "{{ pubsub1.subnet.id }}"
        wait: yes
        region: "us-east-2"
        if_exist_do_not_create: true
        state: present
      register: nat

    - name: Create Private Route Table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "us-east-2"
        tags:
          Name: M5-private-rt
        subnets:
          - "{{ privsub1.subnet.id }}"        
          - "{{ privsub2.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ nat.nat_gateway_id }}"
        state: present
      register: private_route_table

    - name: Create Public Network ACL
      ec2_vpc_nacl:
        vpc_id: "{{ vpc.vpc.id }}"
        name: M5-public-acl       
        region: "us-east-2"
        subnets:
          - "{{ pubsub1.subnet.id }}"        
          - "{{ pubsub2.subnet.id }}"
        ingress:
            # rule no, protocol, allow/deny, cidr, icmp_type, icmp_code, port from, port to
            - [100, 'tcp', 'allow', '68.93.21.221/32', null, null, 443, 443]         
            - [200, 'tcp', 'allow', '0.0.0.0/0', null, null, 22, 22]         
            - [300, 'tcp', 'allow', '24.196.25.139/32', null, null, 443, 443]
            - [400, 'tcp', 'allow', '24.239.105.213/32', null, null, 443, 443]
            - [900, 'tcp', 'allow', '0.0.0.0/0', null, null, 1024, 65535]
        egress:
            - [100, 'tcp', 'allow', '0.0.0.0/0', null, null, 80, 80]         
            - [200, 'tcp', 'allow', '0.0.0.0/0', null, null, 443, 443]
            - [900, 'tcp', 'allow', '0.0.0.0/0', null, null, 1024, 65535]
        state: present 

    - name: Create Private Network ACL
      ec2_vpc_nacl:
        vpc_id: "{{ vpc.vpc.id }}"
        name: M5-private-acl       
        region: "us-east-2"
        subnets:
          - "{{ privsub1.subnet.id }}"        
          - "{{ privsub2.subnet.id }}"
        ingress:
            # rule no, protocol, allow/deny, cidr, icmp_type, icmp_code, port from, port to
            - [100, 'tcp', 'allow', '10.10.0.0/16', null, null, 5432, 5432]         
        egress:
            - [900, 'tcp', 'allow', '0.0.0.0/0', null, null, 1024, 65535]
        state: present
