---
- hosts: localhost
  gather_facts: no
  tasks:

    - name: Create RDS Subnet Group
      rds_subnet_group:
        state: present
        region: us-east-2
        name: M5-private-dbgrp
        description: "Private subnet group for rds instances"
        subnets:
          - "{{ privsub1.subnet.id }}"
          - "{{ privsub2.subnet.id }}"
      register: dbgrp

#    - name: Create RDS Postgres DB
#      rds:
#        command: create
#        instance_name: m5-image-gallery
#        db_name: m5ig
#        region: us-east-2
#        license_model: postgresql-license
#        db_engine: postgres
#        size: '10'
#        instance_type: db.t2.micro
#        username: postgres
#        password: xang1bl1
#        subnet: "{{ dbgrp.subnet_group.name }}"
#        vpc_security_groups: "{{ postgres_sg.group_id }}" 
#        wait: yes
#      register: rds_db      

    - name: Create RDS Postgres DB
      local_action:
        module: rds
        command: restore
        snapshot: image-gallery-snap
        instance_name: m5-image-gallery
        region: us-east-2
        zone: us-east-2a
        db_engine: postgres
        instance_type: db.t2.micro
        subnet: "{{ dbgrp.subnet_group.name }}"
      register: rds_db      

    - name: Fix RDS security group
      local_action:
        module: rds
        command: modify
        instance_name: m5-image-gallery
        region: us-east-2
        vpc_security_groups: "{{ postgres_sg.group_id }}" 
     
    - debug:
        msg: "The new db endpoint is {{ rds_db.instance.endpoint }}"
