---
all:
  hosts:
    ec2-3-15-204-51.us-east-2.compute.amazonaws.com:
    ec2-3-128-180-161.us-east-2.compute.amazonaws.com:
  children:
    al2:
      hosts: 
        ec2-3-15-204-51.us-east-2.compute.amazonaws.com:
        ec2-3-128-180-161.us-east-2.compute.amazonaws.com:
      vars:
        ansible_user: ec2-user
        ansible_python_interpreter: /usr/bin/python

